In [1]:
from pathlib import Path
import os
from dotenv import load_dotenv
import pandas as pd
load_dotenv()
base_path = Path.home() / Path(os.environ.get("DATA_PATH"))
print(base_path)

/home/aayush/rsys_data


In [2]:
df = pd.read_csv(
   base_path/ Path("MINDlarge_train/behaviors.tsv"), 
    sep="\t",
    names=["impressionId","userId","timestamp","click_history","impressions"])

print(f"The dataset originally consist of {len(df)} number of interactions.")


df.head()

The dataset originally consist of 2232748 number of interactions.


impressionId   userId               timestamp  \
0             1   U87243  11/10/2019 11:30:54 AM   
1             2  U598644   11/12/2019 1:45:29 PM   
2             3  U532401  11/13/2019 11:23:03 AM   
3             4  U593596  11/12/2019 12:24:09 PM   
4             5  U239687   11/14/2019 8:03:01 PM   

                                       click_history  \
0  N8668 N39081 N65259 N79529 N73408 N43615 N2937...   
1  N56056 N8726 N70353 N67998 N83823 N111108 N107...   
2  N128643 N87446 N122948 N9375 N82348 N129412 N5...   
3  N31043 N39592 N4104 N8223 N114581 N92747 N1207...   
4  N65250 N122359 N71723 N53796 N41663 N41484 N11...   

                                         impressions  
0  N78206-0 N26368-0 N7578-0 N58592-0 N19858-0 N5...  
1  N47996-0 N82719-0 N117066-0 N8491-0 N123784-0 ...  
2              N103852-0 N53474-0 N127836-0 N47925-1  
3  N38902-0 N76434-0 N71593-0 N100073-0 N108736-0...  
4  N76209-0 N48841-0 N67937-0 N62235-0 N6307-0 N3...

In [3]:
df['impressions'].dtype

dtype('O')

In [4]:
def process_impression(impression_list):
    list_of_strings = impression_list.split()
    click = [x.split('-')[0] for x in list_of_strings if x.split('-')[1] == '1']
    non_click = [x.split('-')[0] for x in list_of_strings]
    return click,non_click


df['click'], df['presented_slate'] = zip(*df['impressions'].map(process_impression))
df

impressionId   userId               timestamp  \
0                   1   U87243  11/10/2019 11:30:54 AM   
1                   2  U598644   11/12/2019 1:45:29 PM   
2                   3  U532401  11/13/2019 11:23:03 AM   
3                   4  U593596  11/12/2019 12:24:09 PM   
4                   5  U239687   11/14/2019 8:03:01 PM   
...               ...      ...                     ...   
2232743       2232744  U316192   11/13/2019 6:50:02 PM   
2232744       2232745  U451238   11/12/2019 8:54:06 AM   
2232745       2232746  U151246  11/13/2019 12:42:51 PM   
2232746       2232747  U330725   11/12/2019 1:22:57 PM   
2232747       2232748  U500938   11/13/2019 8:10:45 PM   

                                             click_history  \
0        N8668 N39081 N65259 N79529 N73408 N43615 N2937...   
1        N56056 N8726 N70353 N67998 N83823 N111108 N107...   
2        N128643 N87446 N122948 N9375 N82348 N129412 N5...   
3        N31043 N39592 N4104 N8223 N114581 N92747 N1207...   
4        N65250 N122359 N71723 N53796 N41663 N41484 N11...   
...                                                    ...   
2232743  N122359 N37069 N95876 N28787 N73408 N11266 N61321   
2232744                 N12575 N93816 N71643 N87236 N87236   
2232745                                      N27587 N49668   
2232746  N121944 N91510 N42280 N60061 N63032 N125223 N4...   
2232747  N13311 N73573 N36246 N47118 N71728 N105480 N61...   

                                               impressions  \
0        N78206-0 N26368-0 N7578-0 N58592-0 N19858-0 N5...   
1        N47996-0 N82719-0 N117066-0 N8491-0 N123784-0 ...   
2                    N103852-0 N53474-0 N127836-0 N47925-1   
3        N38902-0 N76434-0 N71593-0 N100073-0 N108736-0...   
4        N76209-0 N48841-0 N67937-0 N62235-0 N6307-0 N3...   
...                                                    ...   
2232743      N113723-0 N123683-1 N5287-0 N76677-0 N53474-0   
2232744                 N18861-0 N20990-0 N43085-0 N7937-1   
2232745  N39887-1 N22811-0 N110709-1 N1923-0 N24001-1 N...   
2232746  N18947-0 N88808-1 N10012-0 N38902-0 N33078-0 N...   
2232747  N24701-0 N13161-0 N39403-0 N40310-0 N5287-0 N1...   

                                              click  \
0                  [N94157, N78699, N71090, N31174]   
1                                  [N25587, N36266]   
2                                          [N47925]   
3                                         [N114935]   
4                                          [N86258]   
...                                             ...   
2232743                                   [N123683]   
2232744                                     [N7937]   
2232745  [N39887, N110709, N24001, N127572, N10285]   
2232746                                    [N88808]   
2232747                                   [N126252]   

                                           presented_slate  
0        [N78206, N26368, N7578, N58592, N19858, N58258...  
1        [N47996, N82719, N117066, N8491, N123784, N214...  
2                       [N103852, N53474, N127836, N47925]  
3        [N38902, N76434, N71593, N100073, N108736, N30...  
4        [N76209, N48841, N67937, N62235, N6307, N34254...  
...                                                    ...  
2232743          [N113723, N123683, N5287, N76677, N53474]  
2232744                    [N18861, N20990, N43085, N7937]  
2232745  [N39887, N22811, N110709, N1923, N24001, N7667...  
2232746  [N18947, N88808, N10012, N38902, N33078, N1003...  
2232747  [N24701, N13161, N39403, N40310, N5287, N10398...  

[2232748 rows x 7 columns]

In [5]:
news = pd.read_csv(
    base_path/ Path("MINDsmall_train/news.tsv"), 
    sep="\t",
    names=["itemId","category","subcategory","title","abstract","url","title_entities","abstract_entities"])
print(f"The article data consist in total of {len(news)} number of articles.")
news

The article data consist in total of 51282 number of articles.


itemId   category        subcategory  \
0      N55528  lifestyle    lifestyleroyals   
1      N19639     health         weightloss   
2      N61837       news          newsworld   
3      N53526     health             voices   
4      N38324     health            medical   
...       ...        ...                ...   
51277  N16909    weather  weathertopstories   
51278  N47585  lifestyle    lifestylefamily   
51279   N7482     sports        more_sports   
51280  N34418     sports         soccer_epl   
51281  N44276      autos        autossports   

                                                   title  \
0      The Brands Queen Elizabeth, Prince Charles, an...   
1                          50 Worst Habits For Belly Fat   
2      The Cost of Trump's Aid Freeze in the Trenches...   
3      I Was An NBA Wife. Here's How It Affected My M...   
4      How to Get Rid of Skin Tags, According to a De...   
...                                                  ...   
51277  Adapting, Learning And Soul Searching: Reflect...   
51278  Family says 13-year-old Broadway star died fro...   
51279  St. Dominic soccer player tries to kick cancer...   
51280                       How the Sounders won MLS Cup   
51281                  Best Sports Car Deals for October   

                                                abstract  \
0      Shop the notebooks, jackets, and more that the...   
1      These seemingly harmless habits are holding yo...   
2      Lt. Ivan Molchanets peeked over a parapet of s...   
3      I felt like I was a fraud, and being an NBA wi...   
4      They seem harmless, but there's a very good re...   
...                                                  ...   
51277  Woolsey Fire Anniversary: A community is forev...   
51278                                                NaN   
51279  Sometimes, what happens on the sidelines can b...   
51280  Mark, Jeremiah and Casey were so excited they ...   
51281                                                NaN   

                                                 url  \
0      https://assets.msn.com/labs/mind/AAGH0ET.html   
1      https://assets.msn.com/labs/mind/AAB19MK.html   
2      https://assets.msn.com/labs/mind/AAJgNsz.html   
3      https://assets.msn.com/labs/mind/AACk2N6.html   
4      https://assets.msn.com/labs/mind/AAAKEkt.html   
...                                              ...   
51277  https://assets.msn.com/labs/mind/BBWzQJK.html   
51278  https://assets.msn.com/labs/mind/BBWzQYV.html   
51279  https://assets.msn.com/labs/mind/BBWzQnK.html   
51280  https://assets.msn.com/labs/mind/BBWzQuK.html   
51281  https://assets.msn.com/labs/mind/BBy5rVe.html   

                                          title_entities  \
0      [{"Label": "Prince Philip, Duke of Edinburgh",...   
1      [{"Label": "Adipose tissue", "Type": "C", "Wik...   
2                                                     []   
3                                                     []   
4      [{"Label": "Skin tag", "Type": "C", "WikidataI...   
...                                                  ...   
51277  [{"Label": "Woolsey Fire", "Type": "N", "Wikid...   
51278  [{"Label": "Broadway theatre", "Type": "F", "W...   
51279                                                 []   
51280  [{"Label": "MLS Cup", "Type": "U", "WikidataId...   
51281  [{"Label": "Peugeot RCZ", "Type": "V", "Wikida...   

                                       abstract_entities  
0                                                     []  
1      [{"Label": "Adipose tissue", "Type": "C", "Wik...  
2      [{"Label": "Ukraine", "Type": "G", "WikidataId...  
3      [{"Label": "National Basketball Association", ...  
4      [{"Label": "Skin tag", "Type": "C", "WikidataI...  
...                                                  ...  
51277  [{"Label": "Woolsey Fire", "Type": "N", "Wikid...  
51278                                                 []  
51279                                                 []  
51280           

In [6]:
filtered_df = df[
    (df['click'].apply(lambda x: len(x) >= 5)) &
    (df['presented_slate'].apply(lambda x: 5 <= len(x) <= 10))
]

In [7]:
filtered_df = df[
    (df['click'].apply(lambda x: len(x) >= 5)) &
    (df['presented_slate'].apply(lambda x: 5 <= len(x) <= 10))
]
grouped_filtered_df = filtered_df.sort_values(by='timestamp').groupby('userId').agg({
    'impressions': lambda x: list(x),
    'timestamp': lambda x: list(x),
    'click_history': lambda x: list(x),
    'click': lambda x: list(x),
    'presented_slate': lambda x: list(x),   
}).reset_index()
grouped_filtered_df

userId                                        impressions  \
0    U101709  [N30899-0 N99223-0 N60135-0 N83412-1 N113126-1...   
1    U103720  [N46415-0 N96729-1 N127155-1 N47925-0 N95525-0...   
2    U104641  [N5287-0 N127572-1 N76677-0 N94594-1 N100261-1...   
3    U122862  [N30899-1 N61065-1 N83412-1 N35619-0 N20990-0 ...   
4    U124848  [N100073-1 N18539-1 N20990-1 N38902-1 N7937-0 ...   
..       ...                                                ...   
115    U7529  [N27097-1 N83412-1 N61065-1 N60135-0 N20990-1 ...   
116   U83148  [N27097-0 N113126-1 N83412-1 N100073-1 N20990-...   
117   U83661  [N94157-1 N26368-1 N31174-1 N18478-0 N40282-0 ...   
118   U87645  [N27097-1 N87684-1 N30899-1 N61065-0 N60135-0 ...   
119   U91885  [N100073-0 N61065-0 N27097-1 N30899-1 N43085-0...   

                    timestamp  \
0     [11/12/2019 6:59:20 AM]   
1     [11/13/2019 8:13:59 AM]   
2    [11/13/2019 12:36:39 PM]   
3     [11/12/2019 8:12:09 AM]   
4     [11/12/2019 9:03:00 AM]   
..                        ...   
115   [11/12/2019 6:44:19 AM]   
116   [11/12/2019 6:46:58 AM]   
117   [11/10/2019 2:48:55 PM]   
118   [11/12/2019 7:32:57 AM]   
119   [11/12/2019 8:28:17 AM]   

                                         click_history  \
0    [N48971 N128643 N16894 N71496 N58534 N79511 N6...   
1    [N41959 N15371 N79690 N6958 N94541 N91810 N592...   
2    [N454 N72571 N71068 N79746 N89398 N54393 N6306...   
3    [N84217 N120951 N120773 N102743 N3435 N62427 N...   
4    [N128643 N18389 N28568 N113476 N38742 N104200 ...   
..                                                 ...   
115  [N38098 N48971 N16894 N18690 N110755 N75236 N9...   
116  [N73122 N5454 N51724 N102743 N93512 N112665 N1...   
117                    [N117830 N104498 N66184 N85594]   
118  [N9740 N128643 N18389 N5054 N122025 N49668 N80...   
119  [N39345 N8006 N111006 N129463 N61804 N103817 N...   

                                                 click  \
0         [[N83412, N113126, N100073, N20990, N61065]]   
1          [[N96729, N127155, N72609, N93856, N10802]]   
2          [[N127572, N94594, N100261, N24701, N1923]]   
3            [[N30899, N61065, N83412, N43085, N7937]]   
4    [[N100073, N18539, N20990, N38902, N18861, N35...   
..                                                 ...   
115         [[N27097, N83412, N61065, N20990, N30899]]   
116       [[N113126, N83412, N100073, N30899, N60135]]   
117         [[N94157, N26368, N31174, N37924, N78206]]   
118        [[N27097, N87684, N30899, N100073, N20990]]   
119          [[N27097, N30899, N7937, N20990, N87684]]   

                                       presented_slate  
0    [[N30899, N99223, N60135, N83412, N113126, N10...  
1    [[N46415, N96729, N127155, N47925, N95525, N53...  
2    [[N5287, N127572, N76677, N94594, N100261, N12...  
3    [[N30899, N61065, N83412, N35619, N20990, N430...  
4    [[N100073, N18539, N20990, N38902, N7937, N188...  
..                                                 ...  
115  [[N27097, N83412, N61065, N60135, N20990, N100...  
116  [[N27097, N113126, N83412, N100073, N20990, N4...  
117  [[N94157, N26368, N31174, N18478, N40282, N127...  
118  [[N27097, N87684, N30899, N61065, N60135, N100...  
119  [[N100073, N61065, N27097, N30899, N43085, N79...  

[120 rows x 6 columns]

In [8]:
ls=grouped_filtered_df[grouped_filtered_df['userId'] == 'U10'][['presented_slate'][0]].tolist()
ls

[]

In [9]:
filtered_df_3 = df[
    (df['click'].apply(lambda x: len(x) >= 3)) &
    (df['presented_slate'].apply(lambda x: 5 <= len(x) <= 10))
]

In [10]:
filtered_df_2 = df[
    (df['click'].apply(lambda x: len(x) != 1 or (len(x) == 0 and isinstance(x, list)))) &
    (df['presented_slate'].apply(lambda x: 5 <= len(x)))
].reset_index()

In [11]:
filtered_df_2

index  impressionId   userId               timestamp  \
0             0             1   U87243  11/10/2019 11:30:54 AM   
1             1             2  U598644   11/12/2019 1:45:29 PM   
2            13            14   U95671   11/14/2019 8:28:43 PM   
3            18            19  U419371   11/12/2019 4:15:12 AM   
4            24            25  U552512   11/12/2019 8:51:10 PM   
...         ...           ...      ...                     ...   
615591  2232732       2232733  U510519   11/12/2019 6:24:48 AM   
615592  2232735       2232736  U182931   11/14/2019 6:03:16 AM   
615593  2232737       2232738  U424578  11/13/2019 10:44:02 AM   
615594  2232740       2232741  U189711   11/14/2019 8:17:31 PM   
615595  2232745       2232746  U151246  11/13/2019 12:42:51 PM   

                                            click_history  \
0       N8668 N39081 N65259 N79529 N73408 N43615 N2937...   
1       N56056 N8726 N70353 N67998 N83823 N111108 N107...   
2       N64593 N82779 N33216 N9321 N128643 N64496 N680...   
3       N129790 N59633 N51088 N126521 N882 N45706 N488...   
4       N114076 N83597 N38169 N8402 N3773 N106046 N599...   
...                                                   ...   
615591  N70946 N57593 N9276 N5163 N63379 N40628 N11232...   
615592  N87446 N104938 N49247 N112324 N103181 N84940 N...   
615593  N65123 N63858 N2661 N40628 N98238 N98238 N9892...   
615594  N26834 N86208 N83597 N90359 N91280 N55318 N859...   
615595                                      N27587 N49668   

                                              impressions  \
0       N78206-0 N26368-0 N7578-0 N58592-0 N19858-0 N5...   
1       N47996-0 N82719-0 N117066-0 N8491-0 N123784-0 ...   
2       N62736-0 N52388-0 N16161-0 N127585-0 N88596-0 ...   
3       N113644-0 N22659-0 N59301-0 N78239-0 N91047-0 ...   
4       N5098-1 N82866-0 N58417-0 N74117-0 N33468-0 N2...   
...                                                   ...   
615591  N43085-0 N100073-1 N20990-0 N2750-0 N27097-0 N...   
615592  N18405-0 N76665-0 N25751-0 N5747-0 N85664-0 N4...   
615593  N88472-0 N106659-0 N51686-0 N10285-0 N127836-0...   
615594  N72848-0 N104990-0 N3623-0 N51307-0 N83707-0 N...   
615595  N39887-1 N22811-0 N110709-1 N1923-0 N24001-1 N...   

                                                    click  \
0                        [N94157, N78699, N71090, N31174]   
1                                        [N25587, N36266]   
2                                        [N51048, N39403]   
3                       [N120192, N87838, N95254, N53859]   
4       [N5098, N75494, N47643, N80444, N44037, N18947...   
...                                                   ...   
615591                          [N100073, N30899, N83412]   
615592                                   [N20250, N58641]   
615593                          [N100417, N72609, N93856]   
615594                          [N91238, N86258, N102846]   
615595         [N39887, N110709, N24001, N127572, N10285]   

                                          presented_slate  
0       [N78206, N26368, N7578, N58592, N19858, N58258...  
1       [N47996, N82719, N117066, N8491, N123784, N214...  
2       [N62736, N52388, N16161, N127585, N88596, N433...  
3       [N113644, N22659, N59301, N78239, N91047, N416...  
4       [N5098, N82866, N58417, N74117, N33468, N26837...  
...                                                   ...  
615591  [N43085, N100073, N20990, N2750, N27097, N1217...  
615592  [N18405, N76665, N25751, N5747, N85664, N45522...  
615593  [N88472, N106659, N51686, N10285, N127836, N48...  
615594  [N72848, N104990, N3623, N51307, N83707, N1186...  
615595  [N39887, N22811, N110709, N1923, N24001, N7667...  

[615596 rows x 8 columns]

In [12]:
filtered_df_2_1=filtered_df_2.explode('click', ignore_index=True)
filtered_df_2_1=filtered_df_2_1.drop(columns=['index'])
filtered_df_2_1
# feather_path=base_path/ Path("MINDlarge_train/interaction.feather")
# filtered_df_2_1.to_feather(feather_path)

impressionId   userId               timestamp  \
0                   1   U87243  11/10/2019 11:30:54 AM   
1                   1   U87243  11/10/2019 11:30:54 AM   
2                   1   U87243  11/10/2019 11:30:54 AM   
3                   1   U87243  11/10/2019 11:30:54 AM   
4                   2  U598644   11/12/2019 1:45:29 PM   
...               ...      ...                     ...   
1763133       2232746  U151246  11/13/2019 12:42:51 PM   
1763134       2232746  U151246  11/13/2019 12:42:51 PM   
1763135       2232746  U151246  11/13/2019 12:42:51 PM   
1763136       2232746  U151246  11/13/2019 12:42:51 PM   
1763137       2232746  U151246  11/13/2019 12:42:51 PM   

                                             click_history  \
0        N8668 N39081 N65259 N79529 N73408 N43615 N2937...   
1        N8668 N39081 N65259 N79529 N73408 N43615 N2937...   
2        N8668 N39081 N65259 N79529 N73408 N43615 N2937...   
3        N8668 N39081 N65259 N79529 N73408 N43615 N2937...   
4        N56056 N8726 N70353 N67998 N83823 N111108 N107...   
...                                                    ...   
1763133                                      N27587 N49668   
1763134                                      N27587 N49668   
1763135                                      N27587 N49668   
1763136                                      N27587 N49668   
1763137                                      N27587 N49668   

                                               impressions    click  \
0        N78206-0 N26368-0 N7578-0 N58592-0 N19858-0 N5...   N94157   
1        N78206-0 N26368-0 N7578-0 N58592-0 N19858-0 N5...   N78699   
2        N78206-0 N26368-0 N7578-0 N58592-0 N19858-0 N5...   N71090   
3        N78206-0 N26368-0 N7578-0 N58592-0 N19858-0 N5...   N31174   
4        N47996-0 N82719-0 N117066-0 N8491-0 N123784-0 ...   N25587   
...                                                    ...      ...   
1763133  N39887-1 N22811-0 N110709-1 N1923-0 N24001-1 N...   N39887   
1763134  N39887-1 N22811-0 N110709-1 N1923-0 N24001-1 N...  N110709   
1763135  N39887-1 N22811-0 N110709-1 N1923-0 N24001-1 N...   N24001   
1763136  N39887-1 N22811-0 N110709-1 N1923-0 N24001-1 N...  N127572   
1763137  N39887-1 N22811-0 N110709-1 N1923-0 N24001-1 N...   N10285   

                                           presented_slate  
0        [N78206, N26368, N7578, N58592, N19858, N58258...  
1        [N78206, N26368, N7578, N58592, N19858, N58258...  
2        [N78206, N26368, N7578, N58592, N19858, N58258...  
3        [N78206, N26368, N7578, N58592, N19858, N58258...  
4        [N47996, N82719, N117066, N8491, N123784, N214...  
...                                                    ...  
1763133  [N39887, N22811, N110709, N1923, N24001, N7667...  
1763134  [N39887, N22811, N110709, N1923, N24001, N7667...  
1763135  [N39887, N22811, N110709, N1923, N24001, N7667...  
1763136  [N39887, N22811, N110709, N1923, N24001, N7667...  
1763137  [N39887, N22811, N110709, N1923, N24001, N7667...  

[1763138 rows x 7 columns]

In [34]:
news['num_category'] = news['category'].factorize()[0]
article_category_map = news.set_index('itemId')['num_category'].to_dict()

def get_clicked_category_list(row):
    if pd.notna(row['click_history']):
        # Use a list comprehension to create the list of categories
        categories = [article_category_map.get(article_id, 0) for article_id in row['click']]
        count_categories = [categories.count(i) for i in range(0, 18)]
    else:
        # If 'click_history' is NaN, assign a list of zeros
        count_categories = []
    return count_categories
def get_clicked_hist_category_list(row):
    if pd.notna(row['click_history']):
        # Use a list comprehension to create the list of categories
        categories = [article_category_map.get(article_id, 0) for article_id in row['click_history'].split()]
        count_categories = [categories.count(i) for i in range(0, 18)]
    else:
        # If 'click_history' is NaN, assign a list of zeros
        count_categories = []
    return count_categories

# Apply the function to create the new column
filtered_df_2['clicked_category_list'] = filtered_df_2.apply(get_clicked_category_list, axis=1)
filtered_df_2['clicked_hist_category_list'] = filtered_df_2.apply(get_clicked_hist_category_list, axis=1)
filtered_df_2

index  impressionId   userId               timestamp  \
0             0             1   U87243  11/10/2019 11:30:54 AM   
1             1             2  U598644   11/12/2019 1:45:29 PM   
2            13            14   U95671   11/14/2019 8:28:43 PM   
3            18            19  U419371   11/12/2019 4:15:12 AM   
4            24            25  U552512   11/12/2019 8:51:10 PM   
...         ...           ...      ...                     ...   
615591  2232732       2232733  U510519   11/12/2019 6:24:48 AM   
615592  2232735       2232736  U182931   11/14/2019 6:03:16 AM   
615593  2232737       2232738  U424578  11/13/2019 10:44:02 AM   
615594  2232740       2232741  U189711   11/14/2019 8:17:31 PM   
615595  2232745       2232746  U151246  11/13/2019 12:42:51 PM   

                                            click_history  \
0       N8668 N39081 N65259 N79529 N73408 N43615 N2937...   
1       N56056 N8726 N70353 N67998 N83823 N111108 N107...   
2       N64593 N82779 N33216 N9321 N128643 N64496 N680...   
3       N129790 N59633 N51088 N126521 N882 N45706 N488...   
4       N114076 N83597 N38169 N8402 N3773 N106046 N599...   
...                                                   ...   
615591  N70946 N57593 N9276 N5163 N63379 N40628 N11232...   
615592  N87446 N104938 N49247 N112324 N103181 N84940 N...   
615593  N65123 N63858 N2661 N40628 N98238 N98238 N9892...   
615594  N26834 N86208 N83597 N90359 N91280 N55318 N859...   
615595                                      N27587 N49668   

                                              impressions  \
0       N78206-0 N26368-0 N7578-0 N58592-0 N19858-0 N5...   
1       N47996-0 N82719-0 N117066-0 N8491-0 N123784-0 ...   
2       N62736-0 N52388-0 N16161-0 N127585-0 N88596-0 ...   
3       N113644-0 N22659-0 N59301-0 N78239-0 N91047-0 ...   
4       N5098-1 N82866-0 N58417-0 N74117-0 N33468-0 N2...   
...                                                   ...   
615591  N43085-0 N100073-1 N20990-0 N2750-0 N27097-0 N...   
615592  N18405-0 N76665-0 N25751-0 N5747-0 N85664-0 N4...   
615593  N88472-0 N106659-0 N51686-0 N10285-0 N127836-0...   
615594  N72848-0 N104990-0 N3623-0 N51307-0 N83707-0 N...   
615595  N39887-1 N22811-0 N110709-1 N1923-0 N24001-1 N...   

                                                    click  \
0                        [N94157, N78699, N71090, N31174]   
1                                        [N25587, N36266]   
2                                        [N51048, N39403]   
3                       [N120192, N87838, N95254, N53859]   
4       [N5098, N75494, N47643, N80444, N44037, N18947...   
...                                                   ...   
615591                          [N100073, N30899, N83412]   
615592                                   [N20250, N58641]   
615593                          [N100417, N72609, N93856]   
615594                          [N91238, N86258, N102846]   
615595         [N39887, N110709, N24001, N127572, N10285]   

                                          presented_slate  \
0       [N78206, N26368, N7578, N58592, N19858, N58258...   
1       [N47996, N82719, N117066, N8491, N123784, N214...   
2       [N62736, N52388, N16161, N127585, N88596, N433...   
3       [N113644, N22659, N59301, N78239, N91047, N416...   
4       [N5098, N82866, N58417, N74117, N33468, N26837...   
...                                                   ...   
615591  [N43085, N100073, N20990, N2750, N27097, N1217...   
615592  [N18405, N76665, N25751, N5747, N85664, N45522...   
615593  [N88472, N106659, N51686, N10285, N127836, N48...   
615594  [N72848, N104990, N3623, N51307, N83707, N1186...   
615595  [N39887, N22811, N110709, N1923, N24001, N7667...   

                                    clicked_category_list  \
0       [4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
1       [1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, ...   
2       [1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
3       [4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [41]:
# correlation_matrix = filtered_df_2['clicked_category_list'].apply(pd.Series).corrwith(filtered_df_2['clicked_hist_category_list'].apply(pd.Series))
correlation_matrix = filtered_df_2.apply(lambda x: pd.Series(x['clicked_category_list']).corr(pd.Series(x['clicked_hist_category_list'])), axis=1)
# Print the correlation matrix
print("Correlation Matrix:")
print(correlation_matrix)

Correlation Matrix:
0         0.901166
1         0.748288
2         0.753399
3         0.961908
4         0.792153
            ...   
615591    0.929219
615592    0.942666
615593    0.946243
615594    0.996738
615595    0.833285
Length: 615596, dtype: float64


In [42]:
# import pandas as pd
# import seaborn as sns
# import matplotlib.pyplot as plt
# sns.heatmap([correlation_matrix], annot=True, cmap='coolwarm', fmt=".2f", linewidths=.2)
# plt.title('Correlation Matrix')
# plt.show()

KeyboardInterrupt: 

In [30]:
news[news['itemId'] == 'N8668']

itemId category   subcategory  \
44149  N8668   sports  baseball_mlb   

                                                   title  \
44149  Angels GM hinting at going after Gerrit Cole, ...   

                                                abstract  \
44149  With payroll flexibility and the need to add a...   

                                                 url  \
44149  https://assets.msn.com/labs/mind/BBWBW59.html   

                                          title_entities  \
44149  [{"Label": "Stephen Strasburg", "Type": "P", "...   

                                       abstract_entities  num_category  
44149  [{"Label": "Billy Eppler", "Type": "P", "Wikid...             3

In [13]:
grouped_filtered_df_2 = filtered_df_2_1.sort_values(by='timestamp').groupby('userId').agg({
    'impressions': lambda x: list(x),
    'timestamp': lambda x: list(x),
    'click_history': lambda x: list(x),
    'click': lambda x: list(x),
    'presented_slate': lambda x: list(x),   
}).reset_index()
grouped_filtered_df_2

userId                                        impressions  \
0            U0  [N73137-0 N53751-0 N6865-0 N122343-0 N116601-0...   
1            U1  [N74049-0 N62203-0 N117342-0 N38152-0 N51219-0...   
2          U100  [N58641-0 N76665-0 N84886-0 N20250-1 N125664-0...   
3        U10000  [N41315-0 N24701-0 N93856-0 N75618-0 N95525-0 ...   
4       U100001  [N70822-0 N14338-0 N11682-0 N31879-0 N123077-0...   
...         ...                                                ...   
323475   U99992  [N40664-0 N75391-1 N160-0 N11789-0 N30899-0 N4...   
323476   U99993  [N97369-0 N107542-0 N51166-0 N23920-0 N40996-0...   
323477   U99994  [N14067-0 N88743-0 N24516-0 N127073-0 N18999-0...   
323478   U99996  [N110925-0 N29544-0 N105407-0 N25751-0 N48015-...   
323479   U99998  [N100073-0 N38902-0 N61850-0 N18539-0 N27097-0...   

                                                timestamp  \
0            [11/9/2019 6:44:01 AM, 11/9/2019 6:44:01 AM]   
1       [11/12/2019 2:24:19 PM, 11/12/2019 2:24:19 PM,...   
2          [11/14/2019 6:39:36 AM, 11/14/2019 6:39:36 AM]   
3       [11/13/2019 11:45:01 AM, 11/13/2019 11:45:01 A...   
4          [11/11/2019 2:06:52 PM, 11/11/2019 2:06:52 PM]   
...                                                   ...   
323475  [11/11/2019 7:39:16 PM, 11/11/2019 7:39:16 PM,...   
323476  [11/11/2019 9:18:43 AM, 11/11/2019 9:18:43 AM,...   
323477     [11/11/2019 9:36:05 AM, 11/11/2019 9:36:05 AM]   
323478     [11/14/2019 8:11:11 AM, 11/14/2019 8:11:11 AM]   
323479     [11/12/2019 8:38:13 AM, 11/12/2019 8:38:13 AM]   

                                            click_history  \
0       [N39011 N112324 N78884 N111503 N63941 N68426 N...   
1       [N14639 N27258 N63237 N112729 N42180 N109816 N...   
2       [N99587 N61339 N129790 N12721 N100405 N103530 ...   
3       [N34918 N81659 N128643 N97343 N103301 N92366 N...   
4       [N116367 N121227 N77370 N73122 N21475 N42209 N...   
...                                                   ...   
323475  [N42825 N30249 N129444 N107876 N27430 N70709 N...   
323476  [N67397 N67770 N41129 N128503 N51724 N72187 N9...   
323477  [N94577 N30729 N127177 N14611 N82747 N54416 N3...   
323478  [N113476 N54005 N129955 N14121 N73408 N127336 ...   
323479  [N11631 N56746 N91597 N99305 N2099 N42718 N800...   

                                                    click  \
0                                        [N35189, N38813]   
1       [N17881, N36306, N3075, N26359, N92498, N31958...   
2                                        [N41547, N20250]   
3       [N100539, N103852, N82233, N67358, N10285, N13...   
4                                        [N98178, N47257]   
...                                                   ...   
323475           [N75391, N80790, N17907, N62235, N98412]   
323476         [N50244, N129321, N61384, N122819, N17198]   
323477                                  [N126000, N93674]   
323478                                   [N76665, N56873]   
323479                                  [N30899, N110303]   

                                          presented_slate  
0       [[N73137, N53751, N6865, N122343, N116601, N36...  
1       [[N74049, N62203, N117342, N38152, N51219, N48...  
2       [[N58641, N76665, N84886, N20250, N125664, N10...  
3       [[N41315, N24701, N93856, N75618, N95525, N110...  
4       [[N70822, N14338, N11682, N31879, N123077, N55...  
...                                                   ...  
323475  [[N40664, N75391, N160, N11789, N30899, N47110...  
323476  [[N97369, N107542, N51166, N23920, N40996, N12...  
323477  [[N14067, N88743, N24516, N127073, N18999, N11...  
323478  [[N110925, N29544, N105407, N25751, N48015, N1...  
323479  [[N100073, N38902, N61850, N18539, N27097, N30...  

[323480 rows x 6 columns]

In [32]:
max_length = grouped_filtered_df_2['click'].apply(len).max()
mean_length = grouped_filtered_df_2['click'].apply(len).mean()
min_length = grouped_filtered_df_2['click'].apply(len).min()
mode_length = grouped_filtered_df_2['click'].apply(len).mode().iloc[0]
median_length = grouped_filtered_df_2['click'].apply(len).median()

# Print the results
print("Max length:", max_length)
print("Mean length:", mean_length)
print("Min length:", min_length)
print("Mode length:", mode_length)
print("Median length:", median_length)

Max length: 165
Mean length: 5.450531717571411
Min length: 2
Mode length: 2
Median length: 3.0


In [15]:
grouped_filtered_df_2_t = filtered_df_2_1.sort_values(by='timestamp').groupby('timestamp').agg({
    'impressions': lambda x: list(x),
    'click_history': lambda x: list(x),
    'click': lambda x: list(x),
    'presented_slate': lambda x: list(x),   
}).reset_index()
grouped_filtered_df_2_t

timestamp  \
0       11/10/2019 10:00:00 AM   
1       11/10/2019 10:00:02 AM   
2       11/10/2019 10:00:03 PM   
3       11/10/2019 10:00:04 AM   
4       11/10/2019 10:00:05 AM   
...                        ...   
298707    11/9/2019 9:59:56 AM   
298708    11/9/2019 9:59:57 AM   
298709    11/9/2019 9:59:58 AM   
298710    11/9/2019 9:59:58 PM   
298711    11/9/2019 9:59:59 AM   

                                              impressions  \
0       [N64730-0 N54460-0 N26368-0 N58258-0 N7578-0 N...   
1       [N40282-0 N58258-0 N2591-0 N28809-0 N71090-1 N...   
2       [N32844-0 N107191-0 N19858-0 N91923-0 N109083-...   
3       [N28743-0 N36126-0 N121774-0 N58592-0 N44967-0...   
4       [N118944-0 N27427-0 N78699-0 N126722-0 N35936-...   
...                                                   ...   
298707  [N9935-0 N34971-0 N52101-0 N97499-0 N46106-0 N...   
298708  [N75842-0 N102389-0 N52435-0 N66489-0 N14551-0...   
298709  [N4858-0 N66489-0 N63833-0 N64149-0 N66005-0 N...   
298710  [N4858-0 N3604-0 N84137-0 N25037-0 N26404-0 N7...   
298711  [N122706-0 N6293-0 N52435-0 N118589-0 N65783-0...   

                                            click_history  \
0       [N72046 N47788 N66294 N91514 N48606 N7156 N846...   
1       [N27258 N6408 N80170 N116695 N92191 N36761 N26...   
2       [N125760 N57532 N104554 N104081 N90185 N48971 ...   
3       [N97343 N61509 N17120 N73629 N15551 N69341 N44...   
4       [N2 N107944 N39483 N54533 N112765 N61339 N9740...   
...                                                   ...   
298707  [N126878 N42094 N13604 N106155 N77079 N82476 N...   
298708  [N68431 N120756 N28820 N22756 N90561 N100262 N...   
298709  [N82779 N61041 N104475 N61504 N128965 N64765 N...   
298710  [N83623 N16123 N37770, N83623 N16123 N37770, N...   
298711  [N79583 N80788 N12326 N85389 N127567 N61504 N7...   

                                                    click  \
0                                        [N71090, N31174]   
1                                        [N31174, N71090]   
2                                         [N51158, N3664]   
3       [N80175, N31174, N40282, N117508, N31174, N941...   
4                                        [N4858, N112472]   
...                                                   ...   
298707  [N83568, N63286, N3248, N86828, N15736, N31323...   
298708                                   [N62595, N76810]   
298709  [N99362, N119637, N67206, N119637, N88891, N57...   
298710                   [N70497, N81697, N97946, N93934]   
298711  [N27933, N103105, N8006, N127113, N103397, N52...   

                                          presented_slate  
0       [[N64730, N54460, N26368, N58258, N7578, N1847...  
1       [[N40282, N58258, N2591, N28809, N71090, N5446...  
2       [[N32844, N107191, N19858, N91923, N109083, N5...  
3       [[N28743, N36126, N121774, N58592, N44967, N11...  
4       [[N118944, N27427, N78699, N126722, N35936, N2...  
...                                                   ...  
298707  [[N9935, N34971, N52101, N97499, N46106, N1063...  
298708  [[N75842, N102389, N52435, N66489, N14551, N95...  
298709  [[N4858, N66489, N63833, N64149, N66005, N2793...  
298710  [[N4858, N3604, N84137, N25037, N26404, N76810...  
298711  [[N122706, N6293, N52435, N118589, N65783, N12...  

[298712 rows x 5 columns]

In [31]:
max_length = grouped_filtered_df_2_t['timestamp'].apply(len).max()
mean_length = grouped_filtered_df_2_t['timestamp'].apply(len).mean()
min_length = grouped_filtered_df_2_t['timestamp'].apply(len).min()
mode_length = grouped_filtered_df_2_t['timestamp'].apply(len).mode().iloc[0]
median_length = grouped_filtered_df_2_t['timestamp'].apply(len).median()

# Print the results
print("Max length:", max_length)
print("Mean length:", mean_length)
print("Min length:", min_length)
print("Mode length:", mode_length)
print("Median length:", median_length)

Max length: 22
Mean length: 21.096259942687272
Min length: 20
Mode length: 21
Median length: 21.0


In [64]:
news = pd.read_csv(
    base_path/ Path("MINDlarge_train/news.tsv"), 
    sep="\t",
    names=["itemId","category","subcategory","title","abstract","url","title_entities","abstract_entities"])
print(f"The article data consist in total of {len(news)} number of articles.")
news

The article data consist in total of 101527 number of articles.


itemId   category               subcategory  \
0        N88753  lifestyle           lifestyleroyals   
1        N45436       news  newsscienceandtechnology   
2        N23144     health                weightloss   
3        N86255     health                   medical   
4        N93187       news                 newsworld   
...         ...        ...                       ...   
101522  N115249     sports               more_sports   
101523   N64337    finance       finance-real-estate   
101524  N100102     sports                soccer_epl   
101525   N74617      autos               autossports   
101526   N56840     sports               more_sports   

                                                    title  \
0       The Brands Queen Elizabeth, Prince Charles, an...   
1         Walmart Slashes Prices on Last-Generation iPads   
2                           50 Worst Habits For Belly Fat   
3       Dispose of unwanted prescription drugs during ...   
4       The Cost of Trump's Aid Freeze in the Trenches...   
...                                                   ...   
101522  St. Dominic soccer player tries to kick cancer...   
101523  Mansion Monday: Contemporary Des Moines home i...   
101524                       How the Sounders won MLS Cup   
101525                  Best Sports Car Deals for October   
101526       Shall we dance: Sports stars shake their leg   

                                                 abstract  \
0       Shop the notebooks, jackets, and more that the...   
1       Apple's new iPad releases bring big deals on l...   
2       These seemingly harmless habits are holding yo...   
3                                                     NaN   
4       Lt. Ivan Molchanets peeked over a parapet of s...   
...                                                   ...   
101522  Sometimes, what happens on the sidelines can b...   
101523  Among the perks of this unique Des Moines home...   
101524  Mark, Jeremiah and Casey were so excited they ...   
101525                                                NaN   
101526                                                NaN   

                                                  url  \
0       https://assets.msn.com/labs/mind/AAGH0ET.html   
1       https://assets.msn.com/labs/mind/AABmf2I.html   
2       https://assets.msn.com/labs/mind/AAB19MK.html   
3       https://assets.msn.com/labs/mind/AAISxPN.html   
4       https://assets.msn.com/labs/mind/AAJgNsz.html   
...                                               ...   
101522  https://assets.msn.com/labs/mind/BBWzQnK.html   
101523  https://assets.msn.com/labs/mind/BBWzQq8.html   
101524  https://assets.msn.com/labs/mind/BBWzQuK.html   
101525  https://assets.msn.com/labs/mind/BBy5rVe.html   
101526  https://assets.msn.com/labs/mind/BBzMpnG.html   

                                           title_entities  \
0       [{"Label": "Prince Philip, Duke of Edinburgh",...   
1       [{"Label": "IPad", "Type": "J", "WikidataId": ...   
2       [{"Label": "Adipose tissue", "Type": "C", "Wik...   
3       [{"Label": "Drug Enforcement Administration", ...   
4                                                      []   
...                                                   ...   
101522                                                 []   
101523  [{"Label": "Des Moines, Iowa", "Type": "G", "W...   
101524  [{"Label": "MLS Cup", "Type": "U", "WikidataId...   
101525  [{"Label": "Peugeot RCZ", "Type": "V", "Wikida...   
101526                                                 []   

                                        abstract_entities  
0                                                      []  
1       [{"Label": "IPad", "Type": "J", "WikidataId": ...  
2       [{"Label": "Adipose tissue", "Type": "C", "Wik...  
3                                                      []  
4       [{"Label": "Ukraine", "Type": "G", "WikidataId...  
...                                                   ...  
101522                          

In [65]:
categories = news['category'].unique()

In [66]:
category_num_mapping = {category: num for num, category in enumerate(news['category'].unique())}

# Create a new column 'num' in the news DataFrame based on the mapping
news['num_category'] = news['category'].map(category_num_mapping)

In [67]:
category_num_mapping

{'lifestyle': 0,
 'news': 1,
 'health': 2,
 'sports': 3,
 'weather': 4,
 'entertainment': 5,
 'foodanddrink': 6,
 'autos': 7,
 'travel': 8,
 'video': 9,
 'finance': 10,
 'tv': 11,
 'movies': 12,
 'music': 13,
 'kids': 14,
 'middleeast': 15,
 'games': 16,
 'northamerica': 17}

In [68]:
# for r in filtered_df_2_1[0]:
#     print(r)

In [69]:
news['num_category'] = news['category'].factorize()[0]
article_category_map = news.set_index('itemId')['num_category'].to_dict()
# def get_category_list(row):
#     if pd.notna(row['click_history']):
#         # Use a list comprehension to create the list of categories
#         categories=[0] * 18    
#         for article_id in row['click_history'].split():
            
#             i=article_category_map.get(article_id, -1)
#             if i!=-1:
#                 categories[i]+=1
#     else:
#         # If 'click_history' is NaN, assign an empty list
#         categories = []
#     return categories
def get_category_list(row):
    if pd.notna(row['click_history']):
        # Use a list comprehension to create the list of categories
        categories = [article_category_map.get(article_id, 0) for article_id in row['click_history'].split()]
        count_categories = [categories.count(i) for i in range(0, 18)]
    else:
        # If 'click_history' is NaN, assign a list of zeros
        count_categories = []
    return count_categories

# Apply the function to create the new column
filtered_df_2_1['category_list'] = filtered_df_2_1.apply(get_category_list, axis=1)


In [70]:
filtered_df_2_1

impressionId   userId               timestamp  \
0                28  U552980   11/12/2019 9:07:14 AM   
1                28  U552980   11/12/2019 9:07:14 AM   
2                28  U552980   11/12/2019 9:07:14 AM   
3                35  U115754   11/12/2019 7:19:35 AM   
4                35  U115754   11/12/2019 7:19:35 AM   
...             ...      ...                     ...   
65273       2232508  U460351   11/14/2019 8:49:56 AM   
65274       2232533  U103996   11/12/2019 9:00:33 AM   
65275       2232533  U103996   11/12/2019 9:00:33 AM   
65276       2232621  U452155  11/10/2019 11:54:13 AM   
65277       2232621  U452155  11/10/2019 11:54:13 AM   

                                           click_history  \
0      N116930 N45706 N112740 N101840 N78609 N108115 ...   
1      N116930 N45706 N112740 N101840 N78609 N108115 ...   
2      N116930 N45706 N112740 N101840 N78609 N108115 ...   
3      N64496 N65259 N98596 N104760 N9375 N73039 N142...   
4      N64496 N65259 N98596 N104760 N9375 N73039 N142...   
...                                                  ...   
65273                                      N51166 N59280   
65274  N101868 N99279 N86690 N98847 N121168 N40015 N1...   
65275  N101868 N99279 N86690 N98847 N121168 N40015 N1...   
65276                                                NaN   
65277                                                NaN   

                                             impressions   click  \
0      N38902-0 N7937-0 N18861-0 N43085-0 N20990-1 N1...  N20990   
1      N38902-0 N7937-0 N18861-0 N43085-0 N20990-1 N1...  N61065   
2      N38902-0 N7937-0 N18861-0 N43085-0 N20990-1 N1...  N18539   
3      N43085-0 N61065-0 N87684-1 N100073-0 N30899-0 ...  N87684   
4      N43085-0 N61065-0 N87684-1 N100073-0 N30899-0 ...  N20990   
...                                                  ...     ...   
65273      N25751-0 N105407-1 N29544-0 N76665-0 N29441-1  N29441   
65274  N38902-1 N42187-1 N72485-0 N127357-0 N23744-0 ...  N38902   
65275  N38902-1 N42187-1 N72485-0 N127357-0 N23744-0 ...  N42187   
65276  N78206-1 N18478-0 N94157-0 N27822-0 N31174-0 N...  N78206   
65277  N78206-1 N18478-0 N94157-0 N27822-0 N31174-0 N...  N40282   

                                         presented_slate  \
0      [N38902, N7937, N18861, N43085, N20990, N10007...   
1      [N38902, N7937, N18861, N43085, N20990, N10007...   
2      [N38902, N7937, N18861, N43085, N20990, N10007...   
3      [N43085, N61065, N87684, N100073, N30899, N270...   
4      [N43085, N61065, N87684, N100073, N30899, N270...   
...                                                  ...   
65273          [N25751, N105407, N29544, N76665, N29441]   
65274  [N38902, N42187, N72485, N127357, N23744, N568...   
65275  [N38902, N42187, N72485, N127357, N23744, N568...   
65276  [N78206, N18478, N94157, N27822, N31174, N2636...   
65277  [N78206, N18478, N94157, N27822, N31174, N2636...   

                                           category_list  
0      [0, 2, 0, 2, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, ...  
1      [0, 2, 0, 2, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, ...  
2      [0, 2, 0, 2, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, ...  
3      [4, 12, 2, 0, 0, 3, 1, 0, 3, 0, 8, 4, 2, 5, 0,...  
4      [4, 12, 2, 0, 0, 3, 1, 0, 3, 0, 8, 4, 2, 5, 0,...  
...                                                  ...  
65273  [0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, ...  
65274  [2, 0, 0, 0, 0, 4, 1, 1, 0, 0, 0, 3, 1, 2, 0, ...  
65275  [2, 0, 0, 0, 0, 4, 1, 1, 0, 0, 0, 3, 1, 2, 0, ...  
65276                                                 []  
65277                                                 []  

[65278 rows x 8 columns]

In [71]:
article_category_map.get('N45706', 0)

1

In [72]:
# feather_path=base_path/ Path("MINDlarge_train/category.feather")
# filtered_df_2_1.to_feather(feather_path)

In [73]:
print(article_category_map.get('N88753', 0))
article_category_map
for article_id in filtered_df_2_1['click_history']:
    print(article_id)
    print(type(article_id))
    print(article_category_map.get(article_id, 0))
    break

0
N116930 N45706 N112740 N101840 N78609 N108115 N6079 N122726
<class 'str'>
0


In [74]:
filtered_df_2

index  impressionId   userId               timestamp  \
0           27            28  U552980   11/12/2019 9:07:14 AM   
1           34            35  U115754   11/12/2019 7:19:35 AM   
2          124           125  U564802   11/12/2019 4:59:05 PM   
3          231           232  U385752   11/12/2019 8:18:36 AM   
4          250           251  U587096  11/12/2019 11:49:27 AM   
...        ...           ...      ...                     ...   
30484  2232228       2232229   U64178   11/12/2019 8:07:25 AM   
30485  2232325       2232326   U86128    11/9/2019 5:10:36 AM   
30486  2232507       2232508  U460351   11/14/2019 8:49:56 AM   
30487  2232532       2232533  U103996   11/12/2019 9:00:33 AM   
30488  2232620       2232621  U452155  11/10/2019 11:54:13 AM   

                                           click_history  \
0      N116930 N45706 N112740 N101840 N78609 N108115 ...   
1      N64496 N65259 N98596 N104760 N9375 N73039 N142...   
2      N20986 N56056 N59850 N11079 N108147 N74426 N11...   
3                   N85484 N31043 N126052 N65119 N100063   
4      N27779 N47587 N93049 N15375 N54380 N54360 N117...   
...                                                  ...   
30484  N3960 N31043 N100663 N62401 N4169 N37469 N1164...   
30485                     N129342 N127330 N43418 N110158   
30486                                      N51166 N59280   
30487  N101868 N99279 N86690 N98847 N121168 N40015 N1...   
30488                                                NaN   

                                             impressions  \
0      N38902-0 N7937-0 N18861-0 N43085-0 N20990-1 N1...   
1      N43085-0 N61065-0 N87684-1 N100073-0 N30899-0 ...   
2      N86358-1 N92498-1 N112969-0 N69915-0 N65742-0 ...   
3      N43085-0 N20990-1 N61065-0 N30899-0 N87684-1 N...   
4           N18947-0 N7937-1 N33078-0 N110303-1 N62203-0   
...                                                  ...   
30484  N43085-1 N100073-1 N55806-0 N61065-0 N27097-0 ...   
30485  N14848-0 N65783-1 N118589-0 N43186-0 N62595-1 ...   
30486      N25751-0 N105407-1 N29544-0 N76665-0 N29441-1   
30487  N38902-1 N42187-1 N72485-0 N127357-0 N23744-0 ...   
30488  N78206-1 N18478-0 N94157-0 N27822-0 N31174-0 N...   

                           click  \
0       [N20990, N61065, N18539]   
1               [N87684, N20990]   
2      [N86358, N92498, N100324]   
3               [N20990, N87684]   
4               [N7937, N110303]   
...                          ...   
30484          [N43085, N100073]   
30485           [N65783, N62595]   
30486          [N105407, N29441]   
30487           [N38902, N42187]   
30488           [N78206, N40282]   

                                         presented_slate  
0      [N38902, N7937, N18861, N43085, N20990, N10007...  
1      [N43085, N61065, N87684, N100073, N30899, N270...  
2      [N86358, N92498, N112969, N69915, N65742, N963...  
3      [N43085, N20990, N61065, N30899, N87684, N1000...  
4               [N18947, N7937, N33078, N110303, N62203]  
...                                                  ...  
30484  [N43085, N100073, N55806, N61065, N27097, N209...  
30485  [N14848, N65783, N118589, N43186, N62595, N322...  
30486          [N25751, N105407, N29544, N76665, N29441]  
30487  [N38902, N42187, N72485, N127357, N23744, N568...  
30488  [N78206, N18478, N94157, N27822, N31174, N2636...  

[30489 rows x 8 columns]

In [75]:
import torch
def sampled_user(count_list):
    probabilities_tensor = torch.tensor(count_list, dtype=torch.float32)
    probabilities_normalized = probabilities_tensor / probabilities_tensor.sum()

    # Sample a value based on the probabilities
    sampled_value = torch.multinomial(probabilities_normalized, 1).item()

    # Create the sampled tensor
    sampled_list_tensor = torch.zeros_like(probabilities_tensor, dtype=torch.float32)
    sampled_list_tensor[sampled_value] = 1
    return sampled_list_tensor


In [76]:
sampled_user(filtered_df_2_1['category_list'].loc[0])

tensor([0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [77]:
user_state=torch.Tensor(filtered_df_2_1['category_list'].loc[0])
user_state.shape
print(user_state)


tensor([0., 2., 0., 2., 0., 0., 1., 1., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0.])


In [78]:
items=filtered_df_2_1['presented_slate'].loc[0]
items

['N38902',
 'N7937',
 'N18861',
 'N43085',
 'N20990',
 'N100073',
 'N30899',
 'N27097',
 'N61065',
 'N18539']

In [79]:
import random
item_list = [article_category_map.get(key, []) for key in items]

remaining_items = 30 - len(item_list)
additional_values = random.choices(list(set(range(18)) - set(item_list)), k=remaining_items)

item_list.extend(additional_values)

random.shuffle(item_list)


In [80]:
set(range(18))

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17}

In [81]:
length_of_list = len(item_list)

# Create a list of tensors
tensor_list = [torch.eye(19)[value] for value in item_list]

# Print the result
for i, tensor in enumerate(tensor_list):
    print(f"Tensor for value {item_list[i]}:\n{tensor}")

Tensor for value 4:
tensor([0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.])
Tensor for value 11:
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0.])
Tensor for value 16:
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        0.])
Tensor for value 3:
tensor([0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.])
Tensor for value 9:
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.])
Tensor for value 9:
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.])
Tensor for value 16:
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        0.])
Tensor for value 1:
tensor([0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.])
Tensor for value 15:
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 

In [82]:
user_id = filtered_df_2_1['userId'].loc[5]
timestamp = filtered_df_2_1['timestamp'].loc[5]
clicked_items = filtered_df_2_1[(filtered_df_2_1['userId'] == user_id) & (filtered_df_2_1['timestamp'] == timestamp)]['click'].tolist()
print(clicked_items)



['N86358', 'N92498', 'N100324']


In [84]:
import numpy as np
numpy_array = np.copy(
           filtered_df_2_1["category_list"].loc[20176]
        )
user_state = torch.Tensor(numpy_array)
print(user_state)

tensor([])


In [89]:
filtered_df_2_1.loc[35683]

impressionId                                                 1218852
userId                                                        U53487
timestamp                                     11/14/2019 10:28:43 AM
click_history      N10458 N9375 N103933 N105479 N112801 N78356 N1...
impressions        N102458-0 N51163-1 N105407-0 N120147-0 N76665-...
click                                                         N51163
presented_slate    [N102458, N51163, N105407, N120147, N76665, N1...
category_list      [2, 3, 2, 2, 0, 0, 0, 1, 1, 2, 3, 1, 0, 0, 0, ...
Name: 35683, dtype: object